### ISSUE TITLE
Unable to activate plugin from the latest commit.

### ISSUE THREAD

**Issue by soundslikeinfo** [KaizelZero/obsidian-countdown#2]
This plugin looks ideal. However, I downloaded a clone of the current commit hash 1523ea9f8810b1b1c30d9a019cdb3772ec0bc141.. but I was not able to activate the plugin within Obsidian v1.5.8

**Comment by jimmyt-dev** [comment]
I've updated the plugin and created a release. If you just want the plugin, then follow the installation in the README. If you wanted to build this plugin,  follow [this](https://github.com/obsidianmd/obsidian-sample-plugin?tab=readme-ov-file#first-time-developing-plugins) part of the Official README.

**Comment by soundslikeinfo** [comment]
TIL and this is common with all the Obsidian repos, that I need to extract the plugin files, and not the whole repo.

**Comment by soundslikeinfo** [comment]
Thank you. Your latest release 0.1.1 worked and I was able to activate the plugin.

**Comment by jimmyt-dev** [comment]
Yeah, you need to build it or grab the plugin files. I'm gonna mark this as closed.
